//
// InlineResponse200.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct InlineResponse200: Codable {

    public var page: Int?

    public var results: [MovieListObject]?

    public var totalResults: Int?

    public var totalPages: Int?
    
    public init(page: Int?, results: [MovieListObject]?, totalResults: Int?, totalPages: Int?) { 
        self.page = page
        self.results = results
        self.totalResults = totalResults
        self.totalPages = totalPages
    }
    
    public enum CodingKeys: String, CodingKey { 
        case page
        case results
        case totalResults = "total_results"
        case totalPages = "total_pages"
    }

}
